// <auto-generated />
using System;
using AplicacaoWebMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AplicacaoWebMvc.Migrations
{
    [DbContext(typeof(AplicacaoWebMvcContext))]
    partial class AplicacaoWebMvcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AplicacaoWebMvc.Models.Fichario", b =>
                {
                    b.Property<int>("FicharioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("FicharioId");

                    b.ToTable("Fichario");
                });

            modelBuilder.Entity("AplicacaoWebMvc.Models.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .IsRequired();

                    b.Property<DateTime>("DataDeNascimento");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("EstadoCivil");

                    b.Property<int>("FicharioId");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("PessoaId");

                    b.HasIndex("FicharioId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("AplicacaoWebMvc.Models.RegistroDeDizimo", b =>
                {
                    b.Property<int>("RegistroDeDizimoId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<int?>("PessoaId");

                    b.Property<int>("Status");

                    b.Property<double>("Valor");

                    b.HasKey("RegistroDeDizimoId");

                    b.HasIndex("PessoaId");

                    b.ToTable("RegistroDeDizimo");
                });

            modelBuilder.Entity("AplicacaoWebMvc.Models.Pessoa", b =>
                {
                    b.HasOne("AplicacaoWebMvc.Models.Fichario", "Fichario")
                        .WithMany("ListaDePessoa")
                        .HasForeignKey("FicharioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AplicacaoWebMvc.Models.RegistroDeDizimo", b =>
                {
                    b.HasOne("AplicacaoWebMvc.Models.Pessoa", "Pessoa")
                        .WithMany("Registro")
                        .HasForeignKey("PessoaId");
                });
#pragma warning restore 612, 618
        }
    }
}
